export const mockDemoOrders = [
  {
    orderId: "ORD-001",
    customerName: "John Doe",
    orderDate: "2024-01-20",
    totalAmount: 120.5,
    status: "Shipped",
    paymentMethod: "Efectivo",
  },
  {
    orderId: "ORD-002",
    customerName: "Alice Smith",
    orderDate: "2024-01-22",
    totalAmount: 85.0,
    status: "Delivered",
    paymentMethod: "Mercado Pago",
  },
  {
    orderId: "ORD-003",
    customerName: "Bob Johnson",
    orderDate: "2024-01-25",
    totalAmount: 210.75,
    status: "Pending",
    paymentMethod: "Efectivo",
  },
  {
    orderId: "ORD-004",
    customerName: "Emily Brown",
    orderDate: "2024-01-28",
    totalAmount: 155.2,
    status: "Shipped",
    paymentMethod: "Mercado Pago",
  },
  {
    orderId: "ORD-005",
    customerName: "David Wilson",
    orderDate: "2024-01-30",
    totalAmount: 90.0,
    status: "Delivered",
    paymentMethod: "Efectivo",
  },
]
